version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: castle_app_development
      POSTGRES_USER: castle_app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U castle_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://castle_app:password@db:5432/castle_app_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: bundle exec rails server -b 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache: 